# Import packages

In [1]:
import os
import pandas as pd
import requests
from io import StringIO

# Query Examples

## get_flow_by_place

Return the aggregated movement between the selected place and other places.

In [5]:
# set up your target place
target_place = "54"   # West Virginia' FIPS code (Federal Information Processing Standard)
                    # State FIPS code: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/?cid=nrcs143_013696

# set the parameters of your interested data, including operation, scale, source, place..     
params = {"operation": "get_flow_by_place",
       "source": "twitter",
       "scale": "us_state",
       "place": target_place,
       "begin": "01/01/2020",
       "end": "12/31/2020",
       "direction": "both"}

# obtain data using REST APIs
q = r'http://gis.cas.sc.edu/GeoAnalytics/REST'
r = requests.get(q, params=params)

# put the data into a Pandas DataFrame
df = pd.read_csv(StringIO(r.text), header=None, names=["place", "count"])
df.head()

            place  count
0         Wyoming      5
1          Kansas     95
2       Tennessee    787
3            Ohio   8838
4  South Carolina    474

## get_daily_movement_by_place

Return the daily inter-unit movements between the selected place and other places or the

In [6]:
# set up your target place
target_place = "32003"   # Clark County, NV, Las Vegas city
                       # County FIPS code: https://en.wikipedia.org/wiki/List_of_United_States_FIPS_codes_by_county

# set the parameters of your interested data, including operation, scale, source, place..    
params = {"operation": "get_daily_movement_by_place",
          "scale": "us_county",
          "source": "safegraph",
          "place": target_place,
          "begin": "01/01/2020",
          "end": "12/31/2020",
          "direction": "inflow"}

# obtain data using REST APIs
q = r'http://gis.cas.sc.edu/GeoAnalytics/REST'
r = requests.get(q, params=params)

# put the data into a Pandas DataFrame
df = pd.read_csv(StringIO(r.text), header=None, names=["date", "count"])
df

           date  count
0    2020-01-01  67010
1    2020-01-02  63624
2    2020-01-03  61241
3    2020-01-04  58069
4    2020-01-05  47221
5    2020-01-06  38023
6    2020-01-07  35061
7    2020-01-08  35727
8    2020-01-09  38734
9    2020-01-10  44355
10   2020-01-11  46159
11   2020-01-12  42739
12   2020-01-13  33165
13   2020-01-14  30249
14   2020-01-15  31840
15   2020-01-16  37285
16   2020-01-17  52680
17   2020-01-18  67813
18   2020-01-19  66373
19   2020-01-20  53412
20   2020-01-21  40233
21   2020-01-22  39648
22   2020-01-23  43059
23   2020-01-24  48577
24   2020-01-25  51034
25   2020-01-26  48009
26   2020-01-27  36859
27   2020-01-28  30868
28   2020-01-29  30645
29   2020-01-30  35087
..          ...    ...
336  2020-12-02  15168
337  2020-12-03  16513
338  2020-12-04  21223
339  2020-12-05  24325
340  2020-12-06  21621
341  2020-12-07  17375
342  2020-12-08  15406
343  2020-12-09  14546
344  2020-12-10  16725
345  2020-12-11  20525
346  2020-12-12  23802
347  2020-12-13  21053
348  2020-12-14  16978
349  2020-12-15  14827
350  2020-12-16  15014
351  2020-12-17  16444
352  2020-12-18  21364
353  2020-12-19  25838
354  2020-12-20  25024
355  2020-12-21  22750
356  2020-12-22  22748
357  2020-12-23  24615
358  2020-12-24  25784
359  2020-12-25  24504
360  2020-12-26  37338
361  2020-12-27  37283
362  2020-12-28  34454
363  2020-12-29  33722
364  2020-12-30  36466
365  2020-12-31  38737

[366 rows x 2 columns]

## get_daily_movement_for_all_places

Return the daily movements for all places of a specific geographic level (currently return intra movement).

In [7]:
# set up your target place
target_place = "32003"  # Clark County, NV, Las Vegas city

# set the parameters of your interested data, including operation, scale, source, place..     
params = {"operation": "get_daily_movement_for_all_places",
          "scale": "us_state",
          "source": "twitter",
          "place": target_place,
          "begin": "01/01/2020",
          "end": "12/31/2020"
         }

q = r'http://gis.cas.sc.edu/GeoAnalytics/REST'
r = requests.get(q, params=params)
df = pd.read_csv(StringIO(r.text))
df

         place        date  intra_movement
0      Alabama  2020-01-01             855
1      Alabama  2020-01-02             867
2      Alabama  2020-01-03             968
3      Alabama  2020-01-04             845
4      Alabama  2020-01-05             834
5      Alabama  2020-01-06             928
6      Alabama  2020-01-07             827
7      Alabama  2020-01-08             853
8      Alabama  2020-01-09             939
9      Alabama  2020-01-10             956
10     Alabama  2020-01-11             811
11     Alabama  2020-01-12             769
12     Alabama  2020-01-13             938
13     Alabama  2020-01-16             875
14     Alabama  2020-01-17             987
15     Alabama  2020-01-18             796
16     Alabama  2020-01-19             755
17     Alabama  2020-01-20             836
18     Alabama  2020-01-21             937
19     Alabama  2020-01-22             903
20     Alabama  2020-01-23             944
21     Alabama  2020-01-24             978
22     Alabama  2020-01-25             940
23     Alabama  2020-01-26             834
24     Alabama  2020-01-27             816
25     Alabama  2020-01-28             884
26     Alabama  2020-01-29             838
27     Alabama  2020-01-30             950
28     Alabama  2020-01-31            1034
29     Alabama  2020-02-01             950
...        ...         ...             ...
17512  Wyoming  2020-12-01              16
17513  Wyoming  2020-12-02              23
17514  Wyoming  2020-12-03              14
17515  Wyoming  2020-12-04              22
17516  Wyoming  2020-12-05              19
17517  Wyoming  2020-12-06              21
17518  Wyoming  2020-12-07              23
17519  Wyoming  2020-12-08              19
17520  Wyoming  2020-12-09              17
17521  Wyoming  2020-12-10              23
17522  Wyoming  2020-12-11              35
17523  Wyoming  2020-12-12              30
17524  Wyoming  2020-12-13              13
17525  Wyoming  2020-12-14              19
17526  Wyoming  2020-12-15              17
17527  Wyoming  2020-12-16              27
17528  Wyoming  2020-12-17              25
17529  Wyoming  2020-12-18              20
17530  Wyoming  2020-12-19              20
17531  Wyoming  2020-12-20              24
17532  Wyoming  2020-12-21              21
17533  Wyoming  2020-12-22              23
17534  Wyoming  2020-12-23              21
17535  Wyoming  2020-12-24              23
17536  Wyoming  2020-12-25              17
17537  Wyoming  2020-12-26               9
17538  Wyoming  2020-12-27              13
17539  Wyoming  2020-12-28              18
17540  Wyoming  2020-12-29              17
17541  Wyoming  2020-12-30              18

[17542 rows x 3 columns]

## extract_odt_data

Return the selected OD flows in either temporally aggregated format or daily format. The study area can be specified by a bbox. For SafeGraph daily flows, the days selected need be less than 31.

In [11]:
# set the parameters of your interested data, including operation, scale, source, place..     
params = {"operation": "extract_odt_data",
       "source": "twitter",
       "scale": "us_county",
       "begin": "04/01/2019" ,
       "end": "04/15/2019",
       "bbox": "-90,90,-180,180",
       "type": "daily"}

# obtain data using REST APIs
q = r'http://gis.cas.sc.edu/GeoAnalytics/REST'
r = requests.get(q, params=params)

# put the data into a Pandas DataFrame
df = pd.read_csv(StringIO(r.text))
df

,o_place,d_place,year,month,day,cnt,o_lat,o_lon,d_lat,d_lon
0,21115,21115,2019,4,8,5,37.811,-82.816,37.811,-82.816
1,1099,1001,2019,4,7,1,31.523,-87.335,32.576,-86.681
2,36029,36121,2019,4,12,1,42.969,-78.582,42.867,-78.362
3,17109,17031,2019,4,9,1,40.460,-90.674,42.020,-87.772
4,51550,51550,2019,4,10,100,36.761,-76.289,36.762,-76.294
5,51041,51760,2019,4,12,13,37.441,-77.531,37.532,-77.493
6,49057,49011,2019,4,10,4,41.201,-111.990,41.128,-111.997
7,13121,39001,2019,4,2,1,33.740,-84.449,38.906,-83.347
8,18127,18167,2019,4,8,1,41.499,-87.067,39.486,-87.409
9,26125,42091,2019,4,8,1,42.491,-83.143,40.124,-75.458
10,39003,39095,2019,4,9,1,40.887,-83.899,41.657,-83.575
11,24013,24003,2019,4,3,1,39.577,-76.998,39.133,-76.625
12,37135,37101,2019,4,15,1,35.927,-79.087,35.723,-78.418
13,18043,18079,2019,4,3,1,38.324,-85.823,39.001,-85.631
14,4003,4019,2019,4,6,2,31.526,-110.334,31.874,-110.637
15,10003,51510,2019,4,4,1,39.648,-75.669,38.834,-77.055
16,6037,48355,2019,4,6,1,34.021,-118.412,27.737,-97.432
17,13271,13271,2019,4,6,1,32.019,-83.014,32.019,-83.014
18,54057,24023,2019,4,4,1,39.440,-78.981,39.478,-79.173
19,47037,9009,2019,4,4,1,36.157,-86.770,41.306,-72.930
20,17089,17037,2019,4,15,3,41.867,-88.423,41.949,-88.734
21,36085,34021,2019,4,1,1,40.542,-74.207,40.301,-74.782
22,6075,17137,2019,4,12,1,37.771,-122.436,39.722,-90.075
23,13245,13033,2019,4,6,1,33.463,-82.035,33.094,-82.269
24,22069,22069,2019,4,11,49,31.761,-93.086,31.765,-93.084
25,48351,48245,2019,4,8,1,30.272,-93.786,30.087,-94.129
26,25025,12099,2019,4,5,1,42.314,-71.089,26.456,-80.093
27,6097,6099,2019,4,9,1,38.452,-122.676,37.500,-120.862
28,37151,37067,2019,4,8,1,35.881,-79.951,36.113,-80.084
29,36029,26099,2019,4,11,1,42.539,-78.698,42.581,-83.031
...,...,...,...,...,...,...,...,...,...,...
251160,48439,21093,2019,4,15,1,32.702,-97.136,37.822,-85.768
251161,6085,28089,2019,4,1,1,37.313,-122.043,32.474,-90.134
251162,41059,53005,2019,4,8,1,45.917,-119.343,46.286,-119.284
251163,40031,29011,2019,4,4,1,34.621,-98.423,37.600,-94.279
251164,37125,37051,2019,4,2,1,35.171,-79.421,35.068,-78.964
251165,13031,13121,2019,4,4,1,32.441,-81.801,33.631,-84.470
251166,48091,48113,2019,4,12,1,29.949,-98.231,32.864,-96.961
251167,39101,24031,2019,4,7,1,40.597,-83.181,39.008,-77.018
251168,1073,47011,2019,4,15,1,33.542,-86.794,35.261,-84.909
251169,26099,17031,2019,4,13,1,42.701,-82.959,41.787,-87.746
251170,46099,46129,2019,4,13,1,43.545,-96.731,45.537,-100.436
251171,13303,13067,2019,4,5,1,32.837,-82.743,33.822,-84.644
251172,20171,20171,2019,4,6,1,38.479,-100.910,38.479,-100.910
251173,34001,34029,2019,4,6,1,39.447,-74.649,39.606,-74.350
251174,12011,12097,2019,4,10,1,26.205,-80.231,27.758,-80.995
251175,49035,49039,2019,4,12,18,40.700,-111.944,39.500,-111.547
251176,19153,19099,2019,4,1,2,41.603,-93.690,41.703,-93.057
251177,47183,47015,2019,4,5,3,36.341,-88.845,35.831,-85.979
251178,29097,29145,2019,4,13,3,37.109,-94.430,36.910,-94.421
251179,48379,48347,2019,4,5,1,32.782,-95.733,31.614,-94.649
251180,24041,51037,2019,4,9,1,38.863,-76.096,37.003,-78.597
251181,48145,48145,2019,4,3,2,31.310,-96.892,31.273,-96.985
251182,34023,36071,2019,4,1,2,40.441,-74.485,41.435,-73.997
251183,22017,22017,2019,4,4,140,32.467,-93.800,32.463,-93.801
251184,17043,18157,2019,4,12,1,41.794,-88.081,40.407,-86.847
251185,6041,6097,2019,4,14,3,37.968,-122.532,38.364,-122.703
251186,51570,51177,2019,4,13,1,37.265,-77.397,38.295,-77.554
251187,12043,12057,2019,4,9,1,26.974,-81.291,28.132,-82.449
251188,8031,20159,2019,4,2,1,39.714,-104.922,38.498,-98.320
251189,55033,55133,2019,4,13,1,44.882,-91.904,42.982,-88.240

## extract_odt_data_url

Same as extract_odt_data, but returns a download URL and number of records instead of directly returning the csv data. Works better for extracting large amounts of flows.

In [12]:
# set the parameters of your interested data, including operation, scale, source, place..     
params = {"operation": "extract_odt_data_url",
       "source": "safegraph",
        "scale": "us_tract_sc",
       "begin": "01/01/2019" ,
       "end": "01/10/2019",
       "bbox": "20.19346,49.33148,-125.19531,-64.10156",
       "type": "aggregated"}

# obtain data using REST APIs
print("Querying data...")
q = r'http://gis.cas.sc.edu/GeoAnalytics/REST'
r = requests.get(q, params=params)

download_url, count = r.text.split(",")
print("download_url:", download_url)
print("count:", count)

# download data
file_name = download_url.split('/')[-1]
print("Downloading data...")
download_resp = requests.get(download_url, allow_redirects=True)

# save obtained data
f = open(file_name, 'w')
f.write(download_resp.text)
print("Saved data in:", os.path.join(os.getcwd(), file_name))

# put the data into a Pandas DataFrame
df = pd.read_csv(StringIO(download_resp.text))
df

Querying data...
('download_url:', u'http://gis.cas.sc.edu/GeoAnalytics/download/aggregated_sg_od_2019_tract_sc_01012019_01102019_1616441197842.csv')
('count:', u'701405')
Downloading data...
('Saved data in:', u'/home/zhenlong/notebooks/ODT Flow REST API/aggregated_sg_od_2019_tract_sc_01012019_01102019_1616441197842.csv')

            o_place      d_place  cnt   o_lat    o_lon   d_lat    d_lon
0       12019030203  45075010500    1  30.148  -81.809  33.392  -80.639
1       45059920301  45047970101    6  34.473  -82.090  34.311  -82.183
2       45051060406  45067950200    4  33.752  -79.000  34.199  -79.388
3       45013002201  22051021500    1  32.306  -80.891  30.008  -90.217
4       45077010501  36119014607    1  34.978  -82.626  41.280  -73.878
5       37025041702  45031010600    1  35.469  -80.387  34.377  -80.068
6       45091061900  45091061203    2  34.994  -81.357  34.873  -80.919
7       13135050511  45041000700    1  33.969  -84.081  34.193  -79.748
8       45067950500  45051070200    5  34.175  -79.239  33.855  -79.048
9       12086009030  45075011000    3  25.779  -80.327  33.509  -80.859
10      45045001805  45083020400    2  34.875  -82.345  34.955  -81.945
11      12086003921  45033970600    2  25.838  -80.120  34.313  -79.543
12      13255160400  45007010900    1  33.259  -84.265  34.498  -82.907
13      45045002103  45007010104    3  34.799  -82.406  34.759  -82.551
14      45063021304  45079010304   52  33.991  -81.404  34.084  -81.153
15      45045002301  37183053610    1  34.897  -82.418  35.895  -78.801
16      45079011102  45045003013    6  34.054  -80.969  34.702  -82.261
17      45079011603  45063021402    2  33.987  -80.962  33.914  -81.530
18      45003021400  24043010500    2  33.569  -81.729  39.638  -77.786
19      45019000400  51087200127    1  32.784  -79.934  37.626  -77.578
20      21015070503  45051980100    1  39.028  -84.696  33.678  -78.930
21      45045003015  48201241500    1  34.681  -82.286  29.943  -95.373
22      13135050731  45003021602    1  33.844  -83.932  33.516  -81.706
23      45015020202  45019004702    4  33.433  -80.001  32.794  -79.872
24      45027960300  45027960701  227  33.774  -80.166  33.655  -80.221
25      12099005937  45029970300    7  26.431  -80.159  32.876  -80.743
26      37171930802  45051051700    1  36.380  -80.811  33.662  -78.918
27      45079011502  48141010102    1  34.013  -80.923  31.819 -106.430
28      45051060101  34037373600    1  33.794  -79.040  41.030  -74.739
29      45083023405  45045003103    1  34.859  -82.172  34.665  -82.238
...             ...          ...  ...     ...      ...     ...      ...
701375  45083021700  45021970402    1  34.951  -81.970  35.119  -81.432
701376  45055970200  45055970403   34  34.515  -80.469  34.218  -80.662
701377  45079000700  45079011607    1  34.015  -81.048  33.956  -80.938
701378  45079002604  12086001602    2  33.978  -80.981  25.813  -80.263
701379  45013010300  12021010802    4  32.175  -80.745  26.089  -81.703
701380  45051051000  42003562700    1  33.672  -78.952  40.453  -80.007
701381  22051025104  45077011202    1  29.874  -90.033  34.651  -82.835
701382  45041001503  12103024513    1  34.149  -79.912  27.844  -82.683
701383  25017314301  45069960200    1  42.667  -71.293  34.608  -79.675
701384  45083021402  55081950200    2  35.006  -81.940  43.959  -90.664
701385  45051060101  37081012509    2  33.794  -79.040  36.098  -79.838
701386  45007001100  45045002304    2  34.556  -82.670  34.891  -82.392
701387  45019005100  37021002102    1  32.785  -79.928  35.536  -82.525
701388  56021000300  45057011201    1  41.108 -104.831  34.982  -80.860
701389  45043920700  36061003700    5  33.344  -79.291  40.727  -74.009
701390  45057011202  51710006200    1  34.920  -80.840  36.869  -76.220
701391  45045003903  37089930702    1  34.969  -82.484  35.369  -82.563
701392  45003020801  45077011202    2  33.526  -81.994  34.665  -82.837
701393  45083022303  45075010600    5  35.142  -81.858  33.481  -80.845
701394  37119004400  45057010800    3  35.286  -80.881  34.715  -80.774
701395  24003740702  45041000101    1  39.029  -76.724  34.225  -79.826
701396  45019003113  45063020510    2  32.939  -80.059  34.038  -81.123
701397  45091061301  37067000801    2  34.881  -81.055  36.089  -80.230
701398  45079002100  45063021303    2  33.992  -81.006  34.042  -81.393
701399  45073030401  45045001805    1  34.758  -83.084  34.875  -82.345
701400  45059920502  45083023500   14  34.539  -82.035  34.774  -82.077
701401  45091061705  47157011300    1  35.145  -81.194  35.152  -90.042
701402  45045004101  45045000200   15  35.050  -82.496  34.849  -82.397
701403  45007010200  45073030901    6  34.717  -82.476  34.577  -83.081
701404  45079000200  45079010103    5  34.041  -81.038  34.156  -80.932

[701405 rows x 7 columns]